{
  "formatVersion": "1.1",
  "component": {
    "group": "net.violetc",
    "module": "violetcpluginutil",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "url": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "size": 32360,
          "sha512": "4eda52dce171c3badd70cf0151befaa86486d6737e9215370237940c7be2675620196112a87e45d553e32800cf5262da1027a9cd0ce57f2427ac444c7168a79f",
          "sha256": "cdbd72b4c978ee1d452dbd52f77e457b2e32bb22bac1570978784d760422b937",
          "sha1": "57c85f4daf635461759604c994f70e34b37cfa62",
          "md5": "5842857382adf351d3a22aa8b6c209cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "url": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "size": 32360,
          "sha512": "4eda52dce171c3badd70cf0151befaa86486d6737e9215370237940c7be2675620196112a87e45d553e32800cf5262da1027a9cd0ce57f2427ac444c7168a79f",
          "sha256": "cdbd72b4c978ee1d452dbd52f77e457b2e32bb22bac1570978784d760422b937",
          "sha1": "57c85f4daf635461759604c994f70e34b37cfa62",
          "md5": "5842857382adf351d3a22aa8b6c209cf"
        }
      ]
    }
  ]
}
