{
  "formatVersion": "1.1",
  "component": {
    "group": "net.violetc",
    "module": "violetcpluginutil",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "url": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "size": 28980,
          "sha512": "c9e48b98b0b0ee1f7ecd7f707d514bc745642e857769c8814cd31963c62305f6419028bf19749008bf4061a459916ab7797f1dea48b9df16c33e40d1ac84355a",
          "sha256": "ecf6895d8094eb37cce444e2be44d90a81da7032e667326b724030c865dc3d11",
          "sha1": "53b88e3d87638b7b639709365910173fbfbe99dc",
          "md5": "c6d4d372a2ad0cdbd3af3b7ae9064e00"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "url": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "size": 28980,
          "sha512": "c9e48b98b0b0ee1f7ecd7f707d514bc745642e857769c8814cd31963c62305f6419028bf19749008bf4061a459916ab7797f1dea48b9df16c33e40d1ac84355a",
          "sha256": "ecf6895d8094eb37cce444e2be44d90a81da7032e667326b724030c865dc3d11",
          "sha1": "53b88e3d87638b7b639709365910173fbfbe99dc",
          "md5": "c6d4d372a2ad0cdbd3af3b7ae9064e00"
        }
      ]
    }
  ]
}
