{
  "formatVersion": "1.1",
  "component": {
    "group": "net.violetc",
    "module": "violetcpluginutil",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "url": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "size": 30680,
          "sha512": "11d043d67079133282f27cbbe30a757665a26614b3064892c78e8bb626c0ff869d1a4ad32d9e7155003f68feba9b79943790353137c7735d9e4d4e0de6264757",
          "sha256": "8baa1b279d9223cf1a97d3cd998eb1618839bd1065b7f96899d7abc1c6a46825",
          "sha1": "75a43a7949a800c6f75896afeb7d501f20917fde",
          "md5": "04fc557dab585f7d4d2a9dad2e569b09"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "url": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "size": 30680,
          "sha512": "11d043d67079133282f27cbbe30a757665a26614b3064892c78e8bb626c0ff869d1a4ad32d9e7155003f68feba9b79943790353137c7735d9e4d4e0de6264757",
          "sha256": "8baa1b279d9223cf1a97d3cd998eb1618839bd1065b7f96899d7abc1c6a46825",
          "sha1": "75a43a7949a800c6f75896afeb7d501f20917fde",
          "md5": "04fc557dab585f7d4d2a9dad2e569b09"
        }
      ]
    }
  ]
}
