{
  "formatVersion": "1.1",
  "component": {
    "group": "net.violetc",
    "module": "violetcpluginutil",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "url": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "size": 30245,
          "sha512": "137ba5decf4efe2c1d1131fe916fb343ac1cfe2c2ff5bbc207e35c92da94d981c30f74cd4d9162b835c231695bcaaefd349312fe4008f4a80b2c5a74adfeda84",
          "sha256": "21999b9d0b7b275cf8c151a81b9f6469a2136aa759cb6c4fba64e2e757077f5d",
          "sha1": "147392dba73162b43ab8a05a53d66aa7875fa902",
          "md5": "99cc132cfc45adab3fae403a40f67f1a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "url": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "size": 30245,
          "sha512": "137ba5decf4efe2c1d1131fe916fb343ac1cfe2c2ff5bbc207e35c92da94d981c30f74cd4d9162b835c231695bcaaefd349312fe4008f4a80b2c5a74adfeda84",
          "sha256": "21999b9d0b7b275cf8c151a81b9f6469a2136aa759cb6c4fba64e2e757077f5d",
          "sha1": "147392dba73162b43ab8a05a53d66aa7875fa902",
          "md5": "99cc132cfc45adab3fae403a40f67f1a"
        }
      ]
    }
  ]
}
