{
  "formatVersion": "1.1",
  "component": {
    "group": "net.violetc",
    "module": "violetcpluginutil",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "url": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "size": 28902,
          "sha512": "45e2d0480a99b08d7cf0a8b9fdb31cbd806a7c9f38b66f5666fd48ad7108c41bbd8228c1bc79766212855c865d1c41b7e6d9c13849910a8c60246a38cacd5eb2",
          "sha256": "36ea0004ffbc2f20a8ce7fc02ace533905671171746f4af5cb91a2e847b1acb1",
          "sha1": "cdee7701648570790a5be2ceeadbe63f42262c81",
          "md5": "8319e534fb6a52ee4e1054ca59410d9a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "url": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "size": 28902,
          "sha512": "45e2d0480a99b08d7cf0a8b9fdb31cbd806a7c9f38b66f5666fd48ad7108c41bbd8228c1bc79766212855c865d1c41b7e6d9c13849910a8c60246a38cacd5eb2",
          "sha256": "36ea0004ffbc2f20a8ce7fc02ace533905671171746f4af5cb91a2e847b1acb1",
          "sha1": "cdee7701648570790a5be2ceeadbe63f42262c81",
          "md5": "8319e534fb6a52ee4e1054ca59410d9a"
        }
      ]
    }
  ]
}
