{
  "formatVersion": "1.1",
  "component": {
    "group": "net.violetc",
    "module": "violetcpluginutil",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "url": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "size": 31427,
          "sha512": "31abcd04b56ed7787b4373a211fffa463c381a46382f161c8521b1490dcc55ece8a638fef2c5f6816f627c467e978c8a136e95cb7469a276a1345e2feeaaa0bd",
          "sha256": "ca63f919d4267dca3181ac1d8a943db8c42e6f21bdda5e69e7ad6d3e203f1a8a",
          "sha1": "4c1465cbd2e96f26a0eeb0712066754f1b5c2188",
          "md5": "9588a05f66974d52a09621b752a6f080"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "url": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "size": 31427,
          "sha512": "31abcd04b56ed7787b4373a211fffa463c381a46382f161c8521b1490dcc55ece8a638fef2c5f6816f627c467e978c8a136e95cb7469a276a1345e2feeaaa0bd",
          "sha256": "ca63f919d4267dca3181ac1d8a943db8c42e6f21bdda5e69e7ad6d3e203f1a8a",
          "sha1": "4c1465cbd2e96f26a0eeb0712066754f1b5c2188",
          "md5": "9588a05f66974d52a09621b752a6f080"
        }
      ]
    }
  ]
}
