{
  "formatVersion": "1.1",
  "component": {
    "group": "net.violetc",
    "module": "violetcpluginutil",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "url": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "size": 31253,
          "sha512": "b577f760cc12ea9dbcad1a62f740d7d797355363e5eb961ee7b10befb54d1c4485ce8b38b8ecfcfe8086662f63e9919e3d426746dcebd5c077ee094215594c7d",
          "sha256": "75e6b38c22a6f8ca73162525c662213a6896d96e3bb70372d724772d52da4c38",
          "sha1": "a4357f4f53e2ee5f168f0aa6f62b0c15e1327b16",
          "md5": "a1048be127cbd073abc11ba63a7dccac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "url": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "size": 31253,
          "sha512": "b577f760cc12ea9dbcad1a62f740d7d797355363e5eb961ee7b10befb54d1c4485ce8b38b8ecfcfe8086662f63e9919e3d426746dcebd5c077ee094215594c7d",
          "sha256": "75e6b38c22a6f8ca73162525c662213a6896d96e3bb70372d724772d52da4c38",
          "sha1": "a4357f4f53e2ee5f168f0aa6f62b0c15e1327b16",
          "md5": "a1048be127cbd073abc11ba63a7dccac"
        }
      ]
    }
  ]
}
