{
  "formatVersion": "1.1",
  "component": {
    "group": "net.violetc",
    "module": "violetcpluginutil",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "url": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "size": 29472,
          "sha512": "63a05735058c72c1899ed6af1443d6341e8d024eacae53a9ad8e7602f2ae253ae24ddafd8a62e1162e512d07a9137fcf556730853295d43a6a0b9b3eaeeaa370",
          "sha256": "8424bd1779989cf287d62a1ddb8b84ed388e345ddbb4428515cab92a3c318613",
          "sha1": "8b471f86a8d24aaa75448208057f47298ca3e20b",
          "md5": "f6b7a8166a0126362adcb514824f9d46"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "url": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "size": 29472,
          "sha512": "63a05735058c72c1899ed6af1443d6341e8d024eacae53a9ad8e7602f2ae253ae24ddafd8a62e1162e512d07a9137fcf556730853295d43a6a0b9b3eaeeaa370",
          "sha256": "8424bd1779989cf287d62a1ddb8b84ed388e345ddbb4428515cab92a3c318613",
          "sha1": "8b471f86a8d24aaa75448208057f47298ca3e20b",
          "md5": "f6b7a8166a0126362adcb514824f9d46"
        }
      ]
    }
  ]
}
