{
  "formatVersion": "1.1",
  "component": {
    "group": "net.violetc",
    "module": "violetcpluginutil",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "url": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "size": 28250,
          "sha512": "52b727a876906e080f636d8e9d5d2ab4da9e0e66d1177b7364df623abce3652a7f79938473a27b0b8ad608b614b551f1cb1a2ab5a58fb8e0ca0a64bd271d40e1",
          "sha256": "2f8c1bc7df7f403709b6523d629b30de1b4980807ef3fc226a5fd48e4f6be829",
          "sha1": "378763812d1da3237747c45dac750a7db233c24c",
          "md5": "9647ad527d383b6ad3191d91bf88fda8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "url": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "size": 28250,
          "sha512": "52b727a876906e080f636d8e9d5d2ab4da9e0e66d1177b7364df623abce3652a7f79938473a27b0b8ad608b614b551f1cb1a2ab5a58fb8e0ca0a64bd271d40e1",
          "sha256": "2f8c1bc7df7f403709b6523d629b30de1b4980807ef3fc226a5fd48e4f6be829",
          "sha1": "378763812d1da3237747c45dac750a7db233c24c",
          "md5": "9647ad527d383b6ad3191d91bf88fda8"
        }
      ]
    }
  ]
}
