{
  "formatVersion": "1.1",
  "component": {
    "group": "net.violetc",
    "module": "violetcpluginutil",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "url": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "size": 22048,
          "sha512": "a66e4572e986b0e06be946f837594f76aeeda01975cc1a0228e3eaba54f0f7c5e91717f480ad4b4eafab5d01cb8f190189917a42d785a6a73c0a3d982af5f9f7",
          "sha256": "1cf174a6cdc083c0de30d1eef403733cafbea6b0da4b525eb98c390d35f47d22",
          "sha1": "330b42dec214c7341a3f5b8d8976efebc43ea85f",
          "md5": "9e131c52341e585e652b65c2443fcf01"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "url": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "size": 22048,
          "sha512": "a66e4572e986b0e06be946f837594f76aeeda01975cc1a0228e3eaba54f0f7c5e91717f480ad4b4eafab5d01cb8f190189917a42d785a6a73c0a3d982af5f9f7",
          "sha256": "1cf174a6cdc083c0de30d1eef403733cafbea6b0da4b525eb98c390d35f47d22",
          "sha1": "330b42dec214c7341a3f5b8d8976efebc43ea85f",
          "md5": "9e131c52341e585e652b65c2443fcf01"
        }
      ]
    }
  ]
}
