{
  "formatVersion": "1.1",
  "component": {
    "group": "net.violetc",
    "module": "violetcpluginutil",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "url": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "size": 31426,
          "sha512": "c31251a9dd1011aa49c17360902d56fc27459bc64dd322d9b9ad262bb1676c38cb77cf3a2eba9e57c2afac810eca0299f40a0106d340f5251fd14d25dda70a79",
          "sha256": "fac736e506a076751612b572eef9673deb5fdf58ab1eb100395a2e86b7fded8d",
          "sha1": "042f6b442f3966a2d91d124d94acab608ce1dfe8",
          "md5": "761fe2e1740bb942a3b7862716bd2a4f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "url": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "size": 31426,
          "sha512": "c31251a9dd1011aa49c17360902d56fc27459bc64dd322d9b9ad262bb1676c38cb77cf3a2eba9e57c2afac810eca0299f40a0106d340f5251fd14d25dda70a79",
          "sha256": "fac736e506a076751612b572eef9673deb5fdf58ab1eb100395a2e86b7fded8d",
          "sha1": "042f6b442f3966a2d91d124d94acab608ce1dfe8",
          "md5": "761fe2e1740bb942a3b7862716bd2a4f"
        }
      ]
    }
  ]
}
