{
  "formatVersion": "1.1",
  "component": {
    "group": "net.violetc",
    "module": "violetcpluginutil",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "url": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "size": 22287,
          "sha512": "8aff5320205d33ee0a6faeef29de0f17edc803ac646879db7e486edba33a8911e41dcbf0e6a64c72e8330814ac087ad1d5c0364a901239034857346d9e61f2ad",
          "sha256": "1248fe8b97a6ea17bb653fa5fbeb858be3051c4e53c74a112694f31772962747",
          "sha1": "ed6c355c4c758efad47cb76e20e67e7040ce4456",
          "md5": "4697cca593027f21ae97db862ff34083"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "url": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "size": 22287,
          "sha512": "8aff5320205d33ee0a6faeef29de0f17edc803ac646879db7e486edba33a8911e41dcbf0e6a64c72e8330814ac087ad1d5c0364a901239034857346d9e61f2ad",
          "sha256": "1248fe8b97a6ea17bb653fa5fbeb858be3051c4e53c74a112694f31772962747",
          "sha1": "ed6c355c4c758efad47cb76e20e67e7040ce4456",
          "md5": "4697cca593027f21ae97db862ff34083"
        }
      ]
    }
  ]
}
