{
  "formatVersion": "1.1",
  "component": {
    "group": "net.violetc",
    "module": "violetcpluginutil",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "url": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "size": 33724,
          "sha512": "fee664dcae6e42003c37f07bb7c2ac29c38c6a1d17a09331fc4a615126a57017b6e0b356f2b3a744a34abd648d298c7525c57f8a1683be35ad62319dfb6ef36a",
          "sha256": "c2bc5032724f2756a006717193c904462d5fa21f733e7ec758e55726971e653b",
          "sha1": "2e01706db1bc8dcab67a7694644d1cb0f4c1310f",
          "md5": "4ea2269f1ca4aaf24d50f9f88f3d3fcc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "url": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "size": 33724,
          "sha512": "fee664dcae6e42003c37f07bb7c2ac29c38c6a1d17a09331fc4a615126a57017b6e0b356f2b3a744a34abd648d298c7525c57f8a1683be35ad62319dfb6ef36a",
          "sha256": "c2bc5032724f2756a006717193c904462d5fa21f733e7ec758e55726971e653b",
          "sha1": "2e01706db1bc8dcab67a7694644d1cb0f4c1310f",
          "md5": "4ea2269f1ca4aaf24d50f9f88f3d3fcc"
        }
      ]
    }
  ]
}
