{
  "formatVersion": "1.1",
  "component": {
    "group": "net.violetc",
    "module": "violetcpluginutil",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "url": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "size": 34590,
          "sha512": "97f7abb4c9f444c1dd1a31bf984db2b4a6830d62be9057a4f2346c7bd27c0d74c0bc4669090abc45e644a92bc8b6d11c9ae707923b116e45132dd792686902bb",
          "sha256": "d0969f407ba9764be56bd75b7e166f48c8d2f354bbb69ecb8fa5bbed440cc9f7",
          "sha1": "b26c3d5b85534b16bd6042b49e0f30cd2eb237f6",
          "md5": "935aa97c68a8c370c025e7c5eaba34ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "url": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "size": 34590,
          "sha512": "97f7abb4c9f444c1dd1a31bf984db2b4a6830d62be9057a4f2346c7bd27c0d74c0bc4669090abc45e644a92bc8b6d11c9ae707923b116e45132dd792686902bb",
          "sha256": "d0969f407ba9764be56bd75b7e166f48c8d2f354bbb69ecb8fa5bbed440cc9f7",
          "sha1": "b26c3d5b85534b16bd6042b49e0f30cd2eb237f6",
          "md5": "935aa97c68a8c370c025e7c5eaba34ad"
        }
      ]
    }
  ]
}
