{
  "formatVersion": "1.1",
  "component": {
    "group": "net.violetc",
    "module": "violetcpluginutil",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "url": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "size": 34088,
          "sha512": "a3780c8ba2e589b6f8491b4637026202fa92bd6a176dadcd06787e7fc611fc5bdb9a6cf447093190339b4d2786b46feb54068a23982e00c16781d1d0ad044037",
          "sha256": "588c35796cef3b393ef3e45dbd7581d15f3c2412f69f13e1eda0224ce5b15b5b",
          "sha1": "9688a1ecd7418c61484810c8e2e1c92369c635c5",
          "md5": "634c10929ebb74faac98858f010b104b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "url": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "size": 34088,
          "sha512": "a3780c8ba2e589b6f8491b4637026202fa92bd6a176dadcd06787e7fc611fc5bdb9a6cf447093190339b4d2786b46feb54068a23982e00c16781d1d0ad044037",
          "sha256": "588c35796cef3b393ef3e45dbd7581d15f3c2412f69f13e1eda0224ce5b15b5b",
          "sha1": "9688a1ecd7418c61484810c8e2e1c92369c635c5",
          "md5": "634c10929ebb74faac98858f010b104b"
        }
      ]
    }
  ]
}
