{
  "formatVersion": "1.1",
  "component": {
    "group": "net.violetc",
    "module": "violetcpluginutil",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "url": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "size": 33770,
          "sha512": "04f63d5a070bfb62e11bd012e9ed6f9ef5853c10e952a10765cd125065e4500b0f7c81c7e69af5912248dc1c54d00c69393891d3505853b7ba286688df197209",
          "sha256": "aff1e8dc0f17cc526a1ae8879dfd54174cbaf1824c4486070fea479c11a40f82",
          "sha1": "3eb38a091e0193665c2a959ca05fd0a5e21ce8da",
          "md5": "dbaa057d1ed09d06801dd64ad31c1227"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "url": "violetcpluginutil-1.0-SNAPSHOT.jar",
          "size": 33770,
          "sha512": "04f63d5a070bfb62e11bd012e9ed6f9ef5853c10e952a10765cd125065e4500b0f7c81c7e69af5912248dc1c54d00c69393891d3505853b7ba286688df197209",
          "sha256": "aff1e8dc0f17cc526a1ae8879dfd54174cbaf1824c4486070fea479c11a40f82",
          "sha1": "3eb38a091e0193665c2a959ca05fd0a5e21ce8da",
          "md5": "dbaa057d1ed09d06801dd64ad31c1227"
        }
      ]
    }
  ]
}
